refactor!: reorganize `pluginhelper` pkg
cloudnative-pg/cnpg-i-machinery pull request #56
Opened 2024-08-23 10:09 UTC by armru

2024-08-26 15:32 UTC, gabriele-wolfox commented on pkg/pluginhelper/http/constants.go
> +// ErrNilObject is used when a nill object is passed to the builder.
```suggestion
// ErrNilObject is used when a nil object is passed to the builder.
```

2024-08-26 15:56 UTC, gabriele-wolfox requested changes

2024-08-26 15:56 UTC, gabriele-wolfox commented on pkg/pluginhelper/object/patch_test.go
> +	Context("CreatePatch", func() {
As this Context block is the only one and it shows same message of Describe block, I would remove it.

2024-08-27 09:50 UTC, gabriele-wolfox approved these changes

2024-08-27 09:52 UTC, gabriele-wolfox approved these changes

2024-08-30 10:38 UTC, fcanovai approved these changes

2024-08-30 11:10 UTC, leonardoce approved these changes

2024-08-30 11:50 UTC, merged